name: Release
on:
  push:
    branches: [ "release" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install target
      run: rustup target add wasm32-unknown-unknown
    - name: Install tools
      run: cargo install wasm-bindgen-cli
    - name: Build
      run: cargo build --verbose --release --target wasm32-unknown-unknown
    - name: Generate WASM bindings
      run: wasm-bindgen --out-name browser_maze_bevy --out-dir www/scripts --target web --no-typescript target/wasm32-unknown-unknown/release/browser-maze-bevy.wasm
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: www/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
